AWSTemplateFormatVersion: 2010-09-09
Description: |
  Aws CloudFormation Demo
Resources:
  LogicalID:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-09e67e426f25ce0d7
      InstanceType: t2.micro
      KeyName: 2078_ofc
      SecurityGroups:
        - allow ssh and http
      Tags:
        - Key: Name
          Value: Aws-Demo